Product management implementation - Project Structure and Configurations
thisissvikas/shop-keeper pull request #12
Opened 2021-10-21 11:16 UTC by shubhaangi04

- Created Flyway connection
- Created JPA connection
- Created DAO and DTO

2021-10-21 12:27 UTC, thisissvikas requested changes

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/pom.xml
> +	<description>Shop-Keeper project for Spring Boot</description>
make sense

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/pom.xml
> +			<artifactId>spring-boot-devtools</artifactId>
why did we add this?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/pom.xml
> +			<artifactId>mysql-connector-java</artifactId>
why do we need this?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    id int PRIMARY KEY ,
remove space

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    price decimal(10,2),
space after comma

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    description text,
why are we using text here?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    id int PRIMARY KEY ,
is it better to go with long here? why? why not?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    id int PRIMARY KEY ,
how are we gonna generate this? Do we need any **sequence** or **generators**?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    id int PRIMARY KEY,
same here as well

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +CREATE TABLE products(
What happens in case the table already exists?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +		SpringApplication.run(ProductServiceApplication.class, args);
`SpringApplication.run` What does this do?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +@SpringBootApplication
What do we denote by this annotation?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +@SpringBootApplication
Why do/don't we need a **Component Scan** here?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dao/ProductServiceRepository.java
> +public interface ProductServiceRepository extends CrudRepository<Product, Integer>{
What do the types inside the CrudRepository represent?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dao/ProductServiceRepository.java
> +public interface ProductServiceRepository extends CrudRepository<Product, Integer>{
Why CrudRepository, why not JPARepository? What is the difference and which is more suitable here?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dto/Product.java
> +  @Getter @Setter private float price;
what is the better choice here, float or Float?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
move whatever makes sense to application.yml

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    name varchar(255),
I think we decided to increase the size here?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    created_timestamp timestamp,
Do we not need to mention a format here? What is the format in which this will return the date?

2021-10-21 12:27 UTC, krvikas1011 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    FOREIGN KEY (product_id) REFERENCES products(id)
this does not need a created and updated timestamp?? If yes, please change the design and schema accordingly as well.

2021-10-22 09:34 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/pom.xml
> +			<artifactId>spring-boot-devtools</artifactId>
- Whenever files change in the classpath, spring-boot-devtools will cause the application to restart. We don't need to start the application for new changes to take effect. This reduces the time. Hence, when we make the change and save it, the changes will automatically get loaded without us restarting the spring boot application. 
- spring-boot-devtools module includes an embedded LiveReload server that is used to trigger a browser refresh when a resource is changed. When we will implement the UI, at that time the browser will automatically get refreshed if some changes in the server are encountered.

2021-10-22 09:44 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/pom.xml
> +			<artifactId>mysql-connector-java</artifactId>
To connect to a MySQL database server from a Java application, we need a JDBC driver. The MySQL Connector/J (mysql-connector-java) product is one such JDBC driver.

2021-10-22 09:53 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    description text,
For varchar, we always need to mention the size, but in case of text, we don't have to mention the size. For the description field, we don't know how many characters long it can be, hence instead of coupling it with the size, we use text.

2021-10-25 06:58 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +    id int PRIMARY KEY ,
ID can be of the data type int as it can take up to 4,29,49,67,295 values in case of unsigned which is sufficient for our usecase.

2021-10-25 07:39 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +		SpringApplication.run(ProductServiceApplication.class, args);
The run(Class, String []) method is a static helper that can be used to run a SpringApplication from the specified source. It is used to bootstrap and launch a Spring application from a Java main method.

2021-10-25 08:16 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +@SpringBootApplication
The `@SpringBootApplication` annotation enables apps to use auto-configuration, component scan and be able to define extra configuration on the "application class". It is equivalent to using `@Configuration`, `@EnableAutoConfiguration`, and `@ComponentScan` with their default attributes.
- `@EnableAutoConfiguration`: enable Spring Boot’s auto-configuration mechanism. It attempts to automatically configure our Spring application based on the jar dependencies that we have added
- `@ComponentScan`: enable `@Component` scan on the package where the application is located
- `@Configuration`: allow to register extra beans in the context or import additional configuration classes


Since `@SpringBootApplication` already takes care of `@ComponentScan`, we don't need it here.

2021-10-25 08:23 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dao/ProductServiceRepository.java
> +public interface ProductServiceRepository extends CrudRepository<Product, Integer>{
CrudRepository<T, ID> : 
T : the name of the entity
ID : the type of the ID of the entity

2021-10-25 11:18 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dto/Product.java
> +  @Getter @Setter private float price;
Float is better as having return type as Object in the entity class will have default as null instead of 0.0. This will help us understand that the value is not initialized, as having default value as 0.0f can be confusing in case of float.

2021-10-25 11:26 UTC, shubhaangi04 commented
![image](https://user-images.githubusercontent.com/30390673/138686938-00071657-751d-4709-917b-9edbd6b20eda.png)

2021-10-25 11:51 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dao/ProductServiceRepository.java
> +public interface ProductServiceRepository extends CrudRepository<Product, Integer>{
**CrudRepository**
- CrudRepository is a base interface and extends the Repository interface.
- CrudRepository mainly provides CRUD (Create, Read, Update, Delete) operations.
- Return type of saveAll() method is Iterable.
- Use Case - To perform CRUD operations, define repository extending CrudRepository.

**JpaRepository**
- JpaRepository extends PagingAndSortingRepository that extends CrudRepository.
- JpaRepository provides CRUD and pagination operations, along with additional methods like flush(), saveAndFlush(), and deleteInBatch(), etc.
- Return type of saveAll() method is a List.
- Use Case - To perform CRUD as well as batch operations, define repository extends JpaRepository.

According to our use case, CrudRepository is more suitable here as we don't need the extra methods provided by  the JpaRepository like flush(), saveAndFlush(), and deleteInBatch(), etc.
Also, we don't need methods to do pagination and sorting.

2021-10-26 08:44 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/resources/db/migration/V1__init.sql
> +CREATE TABLE products(
If the table already exists, we get `FlywayValidateException: Validate failed: Migrations have failed validation` error. Hence, it is better to use "if not exists" clause with CREATE TABLE.

2021-10-26 10:32 UTC, thisissvikas requested changes

2021-10-26 10:32 UTC, thisissvikas commented on Product Management Service/Code/product-service/pom.xml
> +	<description>Shop-Keeper application to support end-to-end management of everything that a Shopkeeper needs to deal with on a daily basis.</description>
Is this the complete shopkeeper app or just a product management service?

2021-10-26 10:32 UTC, thisissvikas commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +@SpringBootApplication
Please DO NOT copy paste and answer to the point, in your words, showing what do you understand

2021-10-26 10:32 UTC, thisissvikas commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dao/ProductServiceRepository.java
> +public interface ProductServiceRepository extends CrudRepository<Product, Integer>{
How can you say we do not need pagination here?? If there are 10,000 products in a category, you will show all? And DO NOT COPY PASTE.

2021-10-26 10:32 UTC, thisissvikas commented on Product Management Service/Code/product_management_service.sql
> +    id int unsigned PRIMARY KEY AUTO_INCREMENT,
Why did we make these changes?

2021-10-26 10:32 UTC, thisissvikas commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dto/Product.java
> +  @Getter @Setter private Date updatedTimestamp;
Do we not need any formatting here?? Just the DB formatting is enough?

2021-10-27 06:57 UTC, shubhaangi04 commented on Product Management Service/Code/product_management_service.sql
> +    id int unsigned PRIMARY KEY AUTO_INCREMENT,
By default, int data type in MySQL is signed, which considers IDs from -2,14,74,83,648  to  2,14,74,83,647. Even though the default value of AUTO_INCREMENT clause is 1, we will still have IDs ranging from 1 to 2,14,74,83,647 only if we just use int(signed). With unsigned int, the range is from 0 to 4,29,49,67,295 which gives us double the number of possible entries.

2021-10-27 08:57 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/ProductServiceApplication.java
> +@SpringBootApplication
The `@SpringBootApplication` annotation is equivalent to using `@Configuration`, `@EnableAutoConfiguration`, and `@ComponentScan` annotations. 

- `@Configuration` - A Bean in Spring Boot can be configured using annotation or xml. `@Configuration` annotation helps in Spring annotation based configuration. `@Configuration` annotation indicates that a class declares one or more `@Bean` methods that are processed by the Spring container. The container constructs objects of those types, and all the objects are called Spring beans. 
- `@ComponentScan` - tells Spring in which packages we have annotated classes(components). It scans through the package and sub-packages under it and gets to know where all Spring Beans are present. Without the use of this annotation, we will have to locate and register each bean individually in xml file.
- `@EnableAutoconfiguration` - It allows Spring to automatically create and register beans based on both the included jar files in the classpath and the beans defined by us.

Since `@SpringBootApplication` already takes care of `@ComponentScan`, we don't need it here.

2021-10-27 09:03 UTC, shubhaangi04 commented on Product Management Service/Code/product-service/src/main/java/com/shopkeeper/productservice/dao/ProductServiceRepository.java
> +public interface ProductServiceRepository extends CrudRepository<Product, Integer>{
In that case, it is better to use PagingAndSortingRepository as it extends CrudRepository as well. We will get the features provided by the CrudRepository and methods for pagination and sorting

2021-10-27 09:42 UTC, thisissvikas approved these changes

2021-10-27 09:45 UTC, merged

2021-10-27 09:46 UTC, shubhaangi04 commented
Related to: #6